spring:
  profiles:
    active：
      - default
---
spring:
  profiles: default
  application:
    name: careerpeak-common
  redis:
    host: 39.101.179.31
    password: yy7943RMB
    port: 6379
    timeout: 10000
