spring:
  profiles:
    active：
      - prod
---
spring:
  profiles: prod
  application:
    name: careerpeak-common
  redis:
    host: 172.16.0.45
      password: mieEY52AslgiEJp0IrrfrB
      port: 6379
      timeout: 10000
