spring:
  profiles:
    active：
    - default
---
server:
  port: 18768

spring:
  profiles: default
  application:
    name: careerpeak-member
  datasource:
    url: jdbc:mysql://39.101.179.31/careerpeak-member?useUnicode=true&useOldAliasMetadataBehavior=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: new_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 39.101.179.31
    password: yy7943RMB
    port: 6379
    timeout: 10000


ribbon:
  ReadTimeout: 10000
  # 同一实例最大重试次数，不包括首次调用。默认值为0
  MaxAutoRetries: 0
  # 同一个微服务其他实例的最大重试次数，不包括第一次调用的实例。默认值为1
  MaxAutoRetriesNextServer: 0
  # 是否所有操作（GET、POST等）都允许重试。默认值为false
  OkToRetryOnAllOperations: false


mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 60 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 3 #服务刷新时间配置，每隔这个时间会主动心跳一次

management:
  endpoints:
    web:
      exposure:
        include: "*"

#将sql的入参打印
logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

## 日志配置
logback:
  path: /data/logs
  level: INFO
  moduleName: ${spring.application.name}
